### ISSUE TITLE
Use mypy to type check a project

### ISSUE THREAD

**Issue by paxet** [python-gino/gino-starlette#19]
## Expected Behavior

Mypy should know the types from gino-starlette to check our creations against it

## Actual Behavior

Mypy warns about it. Cannot infer the types because they are not declared

## Steps to Reproduce the Problem

  1.  Clone sample project: https://github.com/python-gino/gino-starlette/tree/master/examples/prod_fastapi_demo
  2.  Install mypy
  3.  Execute mypy

```plaintext
mypy src/
src/gino_fastapi_demo/models/__init__.py:1: error: Skipping analyzing 'gino_starlette': found module but no type hints or library stubs
src/gino_fastapi_demo/models/__init__.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 8 source files)
```

## Specifications

* Python version: 3.9.1
* GINO version: 1.0.1
* Starlette version: 0.13.6
* gino-starlette: 0.1.1

## Solution

Maybe we can do a package with the needed [stubs](https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-type-hints-for-third-party-library) like the one for [sqlalchemy](https://pypi.org/project/sqlalchemy-stubs/) on pypi

I've generated a sample with the instructions provided at mypy documentation

```python
from typing import Any, Optional

from fastapi.applications import FastAPI
from gino.api import Gino as _Gino
from gino.api import GinoExecutor as _Executor
from gino.engine import GinoConnection as _Connection
from gino.engine import GinoEngine as _Engine
from gino.strategies import GinoStrategy
from starlette.types import Receive as Receive
from starlette.types import Scope as Scope
from starlette.types import Send as Send

logger: Any

class StarletteModelMixin:
    @classmethod
    async def get_or_404(cls, *args: Any, **kwargs: Any): ...

class GinoExecutor(_Executor):
    async def first_or_404(self, *args: Any, **kwargs: Any): ...

class GinoConnection(_Connection):
    async def first_or_404(self, *args: Any, **kwargs: Any): ...

class GinoEngine(_Engine):
    connection_cls: Any = ...
    async def first_or_404(self, *args: Any, **kwargs: Any): ...

class StarletteStrategy(GinoStrategy):
    name: str = ...
    engine_cls: Any = ...

class _Middleware:
    app: Any = ...
    db: Any = ...
    def __init__(self, app: Any, db: Any) -> None: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...

class Gino(_Gino):
    model_base_classes: Any = ...
    query_executor: Any = ...
    config: Any = ...
    def __init__(
        self, app: Optional[FastAPI] = ..., *args: Any, **kwargs: Any
    ) -> None: ...
    def init_app(self, app: FastAPI) -> None: ...
    async def first_or_404(self, *args: Any, **kwargs: Any): ...
    async def set_bind(self, bind: Any, loop: Optional[Any] = ..., **kwargs: Any): ...
```

**Comment by Chaostheorie** [comment]
Huh. I will look into it, but I only have limited experience with mypy. @paxet you seem to have more experience on this. Would you be interested in handling/ creating such a package yourself? Otherwise, it might be worth discussing with @wwwjfy and @fantix about mypy being integrated into Gino and/ or the extensions itself.

EDIT: After an initial search, I found [gino-stubs](https://github.com/bryanforbes/gino-stubs/). This package seems to already provide the mentioned stubs.

**Comment by paxet** [comment]
I'm sure @bryanforbes will do better than me, because the project you mention is in an advanced state.
The only problem I see, the lack of a pypi package because: https://github.com/bryanforbes/gino-stubs/issues/19
Thank you both.
