### ISSUE TITLE
gino.exceptions.UninitializedError: Gino engine is not initialized.

### ISSUE THREAD

**Issue by begyy** [python-gino/gino-starlette#2]
## Steps to Reproduce the Problem

  1.  gino.exceptions.UninitializedError: Gino engine is not initialized.
![image](https://user-images.githubusercontent.com/44405438/74103415-aaf62d00-4b6d-11ea-99e1-00c21240372e.png)

2. view 
![image](https://user-images.githubusercontent.com/44405438/74103437-ceb97300-4b6d-11ea-9473-28bdd0ccbfb4.png)
3 settings 
![image](https://user-images.githubusercontent.com/44405438/74103444-d4af5400-4b6d-11ea-9016-1d389d8ed982.png)
4. model
![image](https://user-images.githubusercontent.com/44405438/74103674-f27db880-4b6f-11ea-9877-eec7c8a68637.png)

## Specifications

* Python version: 3.6.5
* GINO version:0.8.5
* Starlette version:0.13.1

**Comment by fantix** [comment]
Thanks for trying this extension in such an early stage! We @YUMEYA are still working on this, please kindly wait for the initial release, or use GINO 0.8 for now.

**Comment by begyy** [comment]
Okey)

**Comment by fantix** [comment]
@begyy Oh sorry I didn't notice the issue is for GINO 0.8.5. I'll leave that to @YUMEYA to solve.

**Comment by YUMEYA** [comment]
Hello @begyy , I can't reproduce in the same conditions. Please double check your postgresql settings, especially the privileges of your user on the database.

**Comment by begyy** [comment]
Hello @YUMEYA I checked the database. on this exemplar https://github.com/python-gino/gino-starlette/blob/master/example/app.py works  does not work on mine:)) Can you show me another example? with a router

**Comment by begyy** [comment]
@YUMEYA can you check my code? https://github.com/begyy/gino_and_starlette_hello_world   ?)

**Comment by YUMEYA** [comment]
@begyy OK, I'll look into it.

**Comment by YUMEYA** [comment]
@begyy I changed your code as following and worked:
1. main.py

```python
import os

import uvicorn
from gino.ext.starlette import Gino
from starlette.applications import Starlette

DB_ARGS = dict(
    host=os.getenv("DB_HOST", "localhost"),
    port=os.getenv("DB_PORT", 5432),
    user=os.getenv("DB_USER", "postgres"),
    password=os.getenv("DB_PASS", ""),
    database=os.getenv("DB_NAME", "gino"),
)
PG_URL = "postgresql://{user}:{password}@{host}:{port}/{database}".format(**DB_ARGS)

# Initialize Starlette app
# Don't pass `route` param here, register route with `app.route()` decorator later in `view.py`.
app = Starlette()

# Initialize Gino object
db = Gino(dsn=PG_URL)
db.init_app(app)

# Import your route functions to make them effective. 
# To prevent cyclic importing (`view.py` and `user.py`
# will import `app` and `db` instances above),
# don't put it at the top of this file. 
from view import *

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=5000)
```

2. view.py

```python
from starlette.responses import JSONResponse
from user import User

# Import starlette app instance from `main.py`.
from main import app

# Register your route.
@app.route("/")
async def homepage(request):
    results = []
    users = await User.query.gino.all()
    for user in users:
        results.append({"id": user.id, "name": user.username})
    return JSONResponse(results)
```

3. user.py

```python
# Import gino instance from main.py
from main import db


class User(db.Model):
    __tablename__ = "gino_users"

    id = db.Column(db.BigInteger(), primary_key=True)
    username = db.Column(db.String(50), default="unnamed")
    password = db.Column(db.String(250))

```

Here's my screenshot:  
![image](https://user-images.githubusercontent.com/17715365/74147098-84072c00-4c3d-11ea-91bc-fabd22009ea1.png)

**Comment by begyy** [comment]
@YUMEYA thanks a lot

**Comment by YUMEYA** [comment]
@begyy You are welcome! Feel free to ask any questions or suggest any ideas on our project! 😊

**Comment by begyy** [comment]
@YUMEYA okey 😄
