### ISSUE TITLE
Prod FastAPI Demo Dockerfile doesn't build image 

### ISSUE THREAD

**Issue by atzisb-kozak** [python-gino/gino-starlette#25]
I try the prod fastAPI demo example on my own machine.

## Expected Behavior

Demo run with docker compose 

## Actual Behavior

Image doesn't build correctly and docker compose cannot up.

## Steps to Reproduce the Problem

  1.  Cloning the repo
  2.  Go to prod_fastapi_demo folder
  3.  run docker compose command

```plaintext
git clone https://github.com/python-gino/gino-starlette
cd gino-starlette/examples/prod_fastapi_demo
docker-compose up
```

## Specifications

* Python version: 3.8
* GINO version: na
* Starlette version: na
* WSL 2 (Ubuntu 20.04 LTS)
* Docker : 20.10.2, build 2291f61
* Docker Compose: 1.29.2, build 5becea4c

![2021-07-30 08_21_11- _fastapi_demo](https://user-images.githubusercontent.com/56533652/127609751-b724d20a-cbf2-451b-8647-f582f45c901e.png)

**Comment by atzisb-kozak** [comment]
I try some test on my side but anyone works 
* add rust on image
* put env var CRYPTOGRAPHY_DONT_BUILD_RUST=1 on app and migrations services
* add pip install --upgrade pip on image
* try install poetry with curl

**Comment by Chaostheorie** [comment]
Huh, that should be fixable. Will take a look at it. Has smth similar the other day

**Comment by Chaostheorie** [comment]
Yeah. The changes should've fixed it. Adding rustup for the build step was enough.

**Comment by wwwjfy** [comment]
can you try again? I upgraded dependencies.
I can't reproduce the issue locally, even in older version.
Ideally we download compiled wheels file, so no need to recompile.

I'm using
Docker version 20.10.8, build 3967b7d
docker-compose version 1.29.2, build 5becea4c
https://github.com/python-gino/gino-starlette/commit/8d62ea9794afb7df5fa4e462266be9df69132749

**Comment by atzisb-kozak** [comment]
I retry building image, work on my side, thanks @Chaostheorie 
Docker version 20.10.2, build 2291f61
docker-compose version 1.29.2, build 5becea4c

**Comment by wwwjfy** [comment]
@atzisb-kozak which one works? master or #27?

**Comment by atzisb-kozak** [comment]
Master branch @wwwjfy

**Comment by wwwjfy** [comment]
Thanks

@Chaostheorie I think we can close #27 then

**Comment by wwwjfy** [comment]
as well as this issue
