### ISSUE TITLE
Please Bump Starlette Version

### ISSUE THREAD

**Issue by hamie96** [python-gino/gino-starlette#31]
## Expected Behavior

No dependency conflicts with FastAPI

## Actual Behavior

Newer FastAPI versions have incompatible Starlette version (72.0+)

## Steps to Reproduce the Problem

  1.  Install FastAPI 72.0 or newer
  2.  See dependencies version error

![image](https://user-images.githubusercontent.com/10397098/156611888-4a004347-86ce-4276-b0ce-22bc21da412f.png)
![image](https://user-images.githubusercontent.com/10397098/156611778-c04b5d87-7750-4343-95ca-24ed7bbdbbeb.png)

## Specifications

* Python version: ^3.9
* GINO version: n/a
* Starlette version: ^0.17.1
* FastAPI version: ^72.0

**Comment by tech-cobber** [comment]
I'm having the same error. Following official [doc](https://python-gino.org/docs/en/1.0/tutorials/fastapi.html#add-dependencies) 

<img width="1047" alt="Снимок экрана 2022-03-11 в 23 44 35" src="https://user-images.githubusercontent.com/50849313/157962893-b5a471bb-a098-4e9c-9a63-985483c41551.png">
