### ISSUE TITLE
Upgrade Starlette version

### ISSUE THREAD

**Issue by zoola969** [python-gino/gino-starlette#32]
## Expected Behavior

No dependency conflict

## Actual Behavior

New Fastapi version causes dependency versions conflict

## Steps to Reproduce the Problem

  1.  Try to freeze dependencies with Fastapi >= 0.76.0 and gino-starlette
  2.  Get an error (pip-tools for example)
![image](https://user-images.githubusercontent.com/34693850/171212106-30b5c013-762f-41a4-89ff-4aa1d0d9047c.png)

Btw, there are newer versions of starlette: 0.20.*
https://github.com/tiangolo/fastapi/pull/4820
https://github.com/tiangolo/fastapi/pull/4936
So, if you just change ^0.17 to ^0.19, it wont work for long

## Specifications

* Python version: 3.10
* GINO version: 1.0.1
* Starlette version: 0.19.1

**Comment by wwwjfy** [comment]
I'm happy to review any pull requests. Not an active user of starlette myself, it's better to verify everything works.

**Comment by hamie96** [comment]
> I'm happy to review any pull requests. Not an active user of starlette myself, it's better to verify everything works.

I don't seem to have the ability to create a PR, but I tested changing to ^.19 and it didn't break any tests.

**Comment by hamie96** [comment]
> I'm happy to review any pull requests. Not an active user of starlette myself, it's better to verify everything works.

I don't seem to have the ability to create a PR, but I tested changing to ^.19 and it didn't break any tests.

**Comment by zoola969** [comment]
@wwwjfy Hi.
 A i've created 2 pull requests [Bump to 0.19](https://github.com/python-gino/gino-starlette/pull/33) and [Bump to 0.20](https://github.com/python-gino/gino-starlette/pull/34) (drop Python 3.6 support)
I tested both versions, all work fine
Pls review

**Comment by wwwjfy** [comment]
thanks. it's updated.
